-- Stage 2: append-only carrier event history.
-- Every event the service accepts lands here, including events too old to change the shipment's
-- current status. The shipments table holds the materialized "now"; this table holds the "how".

CREATE TABLE tracking_events
(
    -- Surrogate key. event_id is the natural key, but an append-only table read in insertion
    -- order benefits from a narrow monotonic primary key.
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY,

    event_id              UUID         NOT NULL,
    shipment_id           UUID         NOT NULL,

    -- Denormalized from shipments on purpose: carrier support queries arrive as "what happened to
    -- SP123456?", and this records the number the carrier itself used, which is the value to
    -- search on even if the shipment record is later corrected.
    tracking_number       VARCHAR(128) NOT NULL,

    carrier_code          VARCHAR(32)  NOT NULL,
    carrier_event_type    VARCHAR(64)  NOT NULL,
    normalized_event_type VARCHAR(32)  NOT NULL,

    event_time            TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    received_at           TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    sequence_number       BIGINT       NOT NULL,

    location              VARCHAR(255),
    description           VARCHAR(512),
    correlation_id        VARCHAR(64)  NOT NULL,
    processing_status     VARCHAR(32)  NOT NULL,

    CONSTRAINT pk_tracking_events PRIMARY KEY (id),

    -- Kafka delivers at least once, so the same event_id will eventually arrive twice. The
    -- constraint is the durable guarantee that history cannot contain it twice, independent of
    -- whatever the consumer is doing. Stage 3 adds the application-side handling that turns the
    -- resulting violation into a recorded duplicate instead of a processing failure.
    CONSTRAINT uq_tracking_events_event_id UNIQUE (event_id),

    CONSTRAINT fk_tracking_events_shipment
        FOREIGN KEY (shipment_id) REFERENCES shipments (shipment_id) ON DELETE CASCADE
);

-- Serves GET /api/shipments/{shipmentId}/events, which orders by event_time then sequence_number.
-- The sort columns are in the index so the ordering needs no sort step.
CREATE INDEX idx_tracking_events_shipment_ordered
    ON tracking_events (shipment_id, event_time, sequence_number);

-- Serves carrier support lookups that start from the tracking number rather than the shipment id.
CREATE INDEX idx_tracking_events_tracking_number
    ON tracking_events (tracking_number, event_time);

-- Serves operational queries over the recent ingest stream across all shipments.
CREATE INDEX idx_tracking_events_received_at
    ON tracking_events (received_at DESC);
